pipeline {
    agent {
        node {
            label "cd_docker_agent"
        }
    }

    stages {
        stage('Inititialization') {
            steps {
                echo 'Initializing Build...'
                checkout scm
                sh '''
                    git -v
                    docker -v
                    docker ps
                    docker compose version
                    terraform -v
                '''
            }
        }
        // stage('Provision') {
        //     steps {
        //         echo "Provisioning Infrastructure..."
        //         withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_cli_credentials']]){
        //             sh '''
        //                 cd infrastructure/terraform
        //                 terraform init
        //                 terraform apply -auto-approve
        //             '''
        //         }
        //     }
        // }
        stage("Deploy") {
            environment {
                EC2_IP = ""
            }
            steps {
                echo 'Deploying...'
                
                checkout scm
                
                script {
                    def ec2Ip = sh( 
                        script: 'cd infrastructure/terraform && terraform output -raw ec2_public_ip', 
                        returnStdout: true 
                    )
                    .trim() 

                    echo "EC2 IP is ${ec2Ip}"
                                
                    sshagent(['ec2_ssh_key']) { 
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@${ec2Ip} uptime"
                        echo "Hello from EC2!"    
                    }
                }
            }
        }
    }
}

