pipeline {
    agent {
        node {
            label "cd_docker_agent"
        }
    }

    stages {
        stage('Inititialization') {
            steps {
                echo 'Initializing Build...'
                checkout scm
                sh '''
                    git -v
                    docker -v
                    docker ps
                    docker compose version
                    terraform -v

                    cd infrastructure/terraform 
                    terraform init
                '''
            }
        }
        // stage('Provision') {
        //     steps {
        //         echo "Provisioning Infrastructure..."
        //         withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_cli_credentials']]){
        //             sh '''
        //                 cd infrastructure/terraform
        //                 terraform init
        //                 terraform apply -auto-approve
        //             '''
        //         }
        //     }
        // }
        stage("Deploy") {
            environment {
                EC2_IP = ""
            }
            steps {
                echo 'Deploying...'

                withCredentials([sshUserPrivateKey(credentialsId: 'ec2_ssh_key', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'userName')]) {           
                    script {
                        def ec2Ip = sh( 
                            script: 'cd infrastructure/terraform && terraform output -raw ec2_public_ip', 
                            returnStdout: true 
                        )
                        .trim() 

                        echo "EC2 IP is ${ec2Ip}"

                        def remote = [:]
                        remote.name = 'EC2'
                        remote.host = ec2Ip
                        remote.user = userName
                        remote.identityFile = identity
                        remote.allowAnyHosts = true

                        sshCommand remote: remote, command: "echo Hello from EC2!"
                        sshCommand remote: remote, command: "ls -la"
                    }
                }
            }
        }
    }
}

