pipeline {
    agent {
        node {
            label "ci_docker_agent"
        }
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials("dockerhub_credentials")
    }

    stages {
        stage('Inititialization') {
            steps {
                echo 'Initializing Build...'
                sh '''
                git -v
                docker -v
                docker ps
                docker compose version
                '''
            }
        }
        stage("Build") {
            steps {
                echo 'Building...'
                checkout scm
                sh '''
                docker compose build --no-cache
                '''
            }
        }
        stage("Testing") {
            steps {
                echo 'Running tests...'
            }
        }
        stage("Pubish") {
            steps {
                echo 'Publishing build...'
                checkout scm
                sh '''
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                docker compose push
                '''
            }        
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}

